name: Deploy to production
on:
  release:
    tags:
     - v*
    types: [ released, edited ]
    if: (github.event.action == 'edited' && github.event.changes.make_latest) || github.event.action == 'released'
jobs:
  deploy-on-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($OWNER:String!,$REPO:String!,$TAG:String!) {
              repository(owner:$OWNER,name:$REPO) {
                release(tagName:$TAG) {
                  isLatest
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          TAG: ${{ github.event.release.tag_name }}
      - if: ${{ fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
        run: echo "This is the latest release, i.e. we should deploy it."
      - if: ${{ !fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
        run: echo "This is not the latest release, i.e. we should not deploy it." && exit 1
