name: Deploy to production
on:
  release:
    tags:
     - v*
    types: [ released, edited ]
    if: (github.event.action == 'edited' && github.event.changes.make_latest == true) || github.event.action == 'released'
jobs:
  deploy-on-latest:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{toJSON(github.event)}}'
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($owner:String!,$repo:String!,$tag:String!) {
              repository(owner:$owner,name:$repo) {
                release(tagName:$tag) {
                  isLatest
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
        run: echo "This is the latest release, i.e. we should deploy it."
      - if: ${{ !fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
        run: |
          echo "::error file=release_flow.yml::This is not the latest release, i.e. we should not deploy it."
          exit 1
